# fly.toml app configuration file generated for late-shape-8799 on 2023-05-05T14:18:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "late-shape-8799"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
