# databases:
#   - name: aditya
#     databaseName: aditya_10td
#     user: aditya_10td_user

# services:
#   - type: web
#     name: aditya
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: "bundle exec puma -C config/puma.rb"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: aditya
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false

databases:
  - name: aditya
    databaseName: aditya_6vzy
    user: aditya_6vzy_user

services:
  - type: web
    name: dashboard
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aditya
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false